# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Cores-SweRV-master/vivado_proj/vivado_proj.cache/wt [current_project]
set_property parent.project_path F:/Cores-SweRV-master/vivado_proj/vivado_proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys-a7-100t:part0:1.0 [current_project]
set_property ip_output_repo f:/Cores-SweRV-master/vivado_proj/vivado_proj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {
  F:/Cores-SweRV-master/snapshots/default/common_defines.vh
  F:/Cores-SweRV-master/design/include/global.h
  F:/Cores-SweRV-master/snapshots/default/pic_map_auto.h
  F:/Cores-SweRV-master/design/include/build.h
}
set_property file_type "Verilog Header" [get_files F:/Cores-SweRV-master/design/include/global.h]
set_property file_type "Verilog Header" [get_files F:/Cores-SweRV-master/snapshots/default/pic_map_auto.h]
set_property file_type "Verilog Header" [get_files F:/Cores-SweRV-master/design/include/build.h]
read_verilog -library xil_defaultlib -sv {
  F:/Cores-SweRV-master/design/lib/beh_lib.sv
  F:/Cores-SweRV-master/design/dbg/dbg.sv
  F:/Cores-SweRV-master/design/include/swerv_types.sv
  F:/Cores-SweRV-master/design/dec/dec.sv
  F:/Cores-SweRV-master/design/dec/dec_decode_ctl.sv
  F:/Cores-SweRV-master/design/dec/dec_gpr_ctl.sv
  F:/Cores-SweRV-master/design/dec/dec_ib_ctl.sv
  F:/Cores-SweRV-master/design/dec/dec_tlu_ctl.sv
  F:/Cores-SweRV-master/design/dec/dec_trigger.sv
  F:/Cores-SweRV-master/design/dma_ctrl.sv
  F:/Cores-SweRV-master/design/exu/exu.sv
  F:/Cores-SweRV-master/design/exu/exu_alu_ctl.sv
  F:/Cores-SweRV-master/design/exu/exu_div_ctl.sv
  F:/Cores-SweRV-master/design/exu/exu_mul_ctl.sv
  F:/Cores-SweRV-master/design/ifu/ifu.sv
  F:/Cores-SweRV-master/design/ifu/ifu_aln_ctl.sv
  F:/Cores-SweRV-master/design/ifu/ifu_bp_ctl.sv
  F:/Cores-SweRV-master/design/ifu/ifu_compress_ctl.sv
  F:/Cores-SweRV-master/design/ifu/ifu_ic_mem.sv
  F:/Cores-SweRV-master/design/ifu/ifu_iccm_mem.sv
  F:/Cores-SweRV-master/design/ifu/ifu_ifc_ctl.sv
  F:/Cores-SweRV-master/design/ifu/ifu_mem_ctl.sv
  F:/Cores-SweRV-master/design/lsu/lsu.sv
  F:/Cores-SweRV-master/design/lsu/lsu_addrcheck.sv
  F:/Cores-SweRV-master/design/lsu/lsu_bus_buffer.sv
  F:/Cores-SweRV-master/design/lsu/lsu_bus_intf.sv
  F:/Cores-SweRV-master/design/lsu/lsu_clkdomain.sv
  F:/Cores-SweRV-master/design/lsu/lsu_dccm_ctl.sv
  F:/Cores-SweRV-master/design/lsu/lsu_dccm_mem.sv
  F:/Cores-SweRV-master/design/lsu/lsu_ecc.sv
  F:/Cores-SweRV-master/design/lsu/lsu_lsc_ctl.sv
  F:/Cores-SweRV-master/design/lsu/lsu_stbuf.sv
  F:/Cores-SweRV-master/design/lsu/lsu_trigger.sv
  F:/Cores-SweRV-master/design/mem.sv
  F:/Cores-SweRV-master/design/lib/mem_lib.sv
  F:/Cores-SweRV-master/design/pic_ctrl.sv
  F:/Cores-SweRV-master/design/dmi/rvjtag_tap.sv
  F:/Cores-SweRV-master/design/swerv.sv
  F:/Cores-SweRV-master/design/swerv_wrapper.sv
}
read_verilog -library xil_defaultlib {
  F:/Cores-SweRV-master/design/dmi/dmi_jtag_to_core_sync.v
  F:/Cores-SweRV-master/design/dmi/dmi_wrapper.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top swerv_wrapper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef swerv_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file swerv_wrapper_utilization_synth.rpt -pb swerv_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
